apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
  labels:
    app: infra
spec:
  replicas: 5
  selector:
    matchLabels:
      app: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      containers:
        - name: infra
          image: rg.nl-ams.scw.cloud/genericdevelopment/infra:1.0.0
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "200m"
#            limits:
#              memory: "256Mi"
#              cpu: "250m"
          ports:
            - containerPort: 3000
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 600

      imagePullSecrets:
        - name: regcred
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - infra.tigo.tech
      secretName: echo-tls
  rules:
    - host: infra.tigo.tech
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: infra
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: infra
spec:
  type: NodePort
  selector:
    app: infra
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000